services:
  chandaliar:
    build: .
    restart: always
    ports:
      - 8081:8080
    environment:
      MQTT_HOST: rabbitmq
    env_file:
      - server/mobile-server/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    logging:
      driver: none
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
