services:
  chandaliar:
    build: 
      context: .
      args:
        CONFIG_ENV: jungletalk
    restart: always
    ports:
      - 8081:8080
    environment:
      MQTT_HOST: rabbitmq
      MQTT_ENABLED: "true"
      OPENAI_API_MODEL: "gpt-4-0125-preview"
    env_file:
      - server/mobile-server/.env
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3
    restart: always
    ports:
      - 15672:15672
      - 5672:5672
      - 1883:1883
    logging:
      driver: none
    volumes:
      - "./rabbit_enabled_plugins:/etc/rabbitmq/enabled_plugins"
